name: lvm_telephony_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.4.0
  slang: ^3.30.2
  build_runner: ^2.4.9
  flutter_svg: ^2.0.10+1
  auto_route: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.6
  
  domain: 
    path: ../../packages/domain
  common: 
    path: ../../packages/common
  core: 
    path: ../../packages/core
  data: 
    path: ../../packages/data
  flutter_localization: 
    path: ../../packages/external/flutter_localization
  injectable: ^2.4.1
  get_it: ^7.6.8
  injectable_generator: ^2.6.1
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.5
  logger: ^2.2.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  dartz: ^0.10.1
  mask_text_input_formatter: ^2.9.0
  mocktail: ^1.0.3
  # flutter_secure_storage: ^9.2.2
  flutter_secure_storage_web: ^2.0.0-beta.1
  loading_animation_widget: ^1.2.1
  another_flushbar: ^1.12.30
  just_audio: ^0.9.42
  audioplayers: ^6.0.0
  expansion_tile_card: ^3.0.0
  intl: ^0.19.0
  date_picker_plus: ^4.1.0
  day_night_time_picker: ^1.3.1
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  url_strategy: ^0.3.0
  pluto_grid: ^8.0.0
  pointer_interceptor: ^0.10.1+2

# dependency_overrides:
#   flutter_secure_storage_web: ^2.0.0-beta.1

dev_dependencies:
  flutter_lints: ^2.0.0
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/app_bar/
    - assets/icons/drawer/
    - assets/icons/calls/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 100
  integrations: 
    flutter_svg: true