targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: ru
          fallback_strategy: base_locale
          string_interpolation: dart
          input_directory: i18n
          input_file_pattern: .i18n.json
          namespaces: true
          output_directory: lib/gen
          output_file_name: translations.g.dart
          output_format: single_file
          locale_handling: true
          flutter_integration: false
          translate_var: t
          enum_name: AppLocale
          translation_class_visibility: private
          key_case: camel
          key_map_case: camel
          param_case: camel