name: core
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  dartz: ^0.10.1
  get_it: ^7.7.0
  injectable: ^2.4.1


dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  lints: ^3.0.0
  test: ^1.24.0
