name: domain
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.9
  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.0
  injectable_generator: ^2.6.1
  path: ^1.8.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^3.0.0
  freezed: ^2.5.3
  lints: ^3.0.0
  test: ^1.24.0
